// <auto-generated />
using AdminBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdminBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260416084719_AddProjectsSeed")]
    partial class AddProjectsSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("AdminBackend.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abstract")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRevealed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResearchAreaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SupervisorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ResearchAreaId");

                    b.HasIndex("SupervisorId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abstract = "Developing an AI system to assist in code reviews",
                            IsRevealed = false,
                            ResearchAreaId = 1,
                            StudentName = "John Doe",
                            SupervisorId = 1,
                            Title = "AI-Powered Code Review System"
                        },
                        new
                        {
                            Id = 2,
                            Abstract = "Analyzing security vulnerabilities in blockchain implementations",
                            IsRevealed = true,
                            ResearchAreaId = 2,
                            StudentName = "Jane Smith",
                            SupervisorId = 2,
                            Title = "Blockchain Security Analysis"
                        },
                        new
                        {
                            Id = 3,
                            Abstract = "Optimizing React applications for better performance",
                            IsRevealed = false,
                            ResearchAreaId = 3,
                            StudentName = "Bob Wilson",
                            SupervisorId = 3,
                            Title = "React Performance Optimization"
                        });
                });

            modelBuilder.Entity("AdminBackend.Models.ResearchArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ResearchAreas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "AI and Machine Learning research",
                            Name = "Artificial Intelligence"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Network security and cryptography",
                            Name = "Cybersecurity"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Modern web technologies and frameworks",
                            Name = "Web Development"
                        });
                });

            modelBuilder.Entity("AdminBackend.Models.Supervisor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Supervisors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "Computer Science",
                            Name = "Dr. Alice Johnson"
                        },
                        new
                        {
                            Id = 2,
                            Department = "Information Security",
                            Name = "Prof. Bob Smith"
                        },
                        new
                        {
                            Id = 3,
                            Department = "Software Engineering",
                            Name = "Dr. Carol Williams"
                        },
                        new
                        {
                            Id = 4,
                            Department = "Data Science",
                            Name = "Prof. David Brown"
                        });
                });

            modelBuilder.Entity("AdminBackend.Models.Project", b =>
                {
                    b.HasOne("AdminBackend.Models.ResearchArea", "ResearchArea")
                        .WithMany("Projects")
                        .HasForeignKey("ResearchAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdminBackend.Models.Supervisor", "Supervisor")
                        .WithMany("Projects")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResearchArea");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("AdminBackend.Models.ResearchArea", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("AdminBackend.Models.Supervisor", b =>
                {
                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
